### ISSUE TITLE
Editing/Changing names of objects, environments, functional roles does not save

### ISSUE THREAD

**Issue by sfc-gh-mybarra** [Snowflake-Labs/roleout#1] opened 2023-04-20 15:20 UTC
I changed environment names using the edit (pencil icon) and saved my project. When I moved on to DBs, VWH, etc., those changes were not applied to my project. I moved back to the environment page, and my changes were not saved. I edited the environment names again, saved my project, and closed Roleout. I then opened the project again, and my changes were not saved.

I found that deleting the environment names and creating new names did save. Because of this, I had to reset all the parameters and access configurations for my project. I did a test on the database page and experienced the same issue.

**Comment by sfc-gh-ckite** [comment] 2023-04-20 16:27
After discussion, we found that the user had not clicked the checkmark to save the new name. Closing as working as intended.

**Closed** 2023-04-20 16:27 UTC
